// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CreditCardSystem.Models
{
    public partial class CardType
    {
        public Guid CardTypeId { get; set; }
        public string CardTypeName { get; set; }
        public bool IsActive { get; set; }
    }
}