// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CreditCardSystem.Models
{
    public partial class CreditCardSystemContext : DbContext
    {
        public CreditCardSystemContext()
        {
        }

        public CreditCardSystemContext(DbContextOptions<CreditCardSystemContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CardType> CardType { get; set; }
        public virtual DbSet<CreditCard> CreditCard { get; set; }
        public virtual DbSet<ValidationRegex> ValidationRegex { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CardType>(entity =>
            {
                entity.Property(e => e.CardTypeId).ValueGeneratedNever();

                entity.Property(e => e.CardTypeName)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsFixedLength();

                entity.HasOne(d => d.ValidationRegex)
                    .WithMany(p => p.CardType)
                    .HasForeignKey(d => d.ValidationRegexId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__CardType__Valida__5FB337D6");
            });

            modelBuilder.Entity<CreditCard>(entity =>
            {
                entity.Property(e => e.CreditCardId).ValueGeneratedNever();

                entity.Property(e => e.CardCvv)
                    .IsRequired()
                    .HasMaxLength(4)
                    .HasColumnName("CardCVV")
                    .IsFixedLength();

                entity.Property(e => e.CardExpiry).HasColumnType("date");

                entity.Property(e => e.CardNumber)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.CardType)
                    .WithMany(p => p.CreditCard)
                    .HasForeignKey(d => d.CardTypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CreditCard_CardType");
            });

            modelBuilder.Entity<ValidationRegex>(entity =>
            {
                entity.Property(e => e.ValidationRegexId).ValueGeneratedNever();

                entity.Property(e => e.ValidationRegexName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.ValidationRegexString)
                    .IsRequired()
                    .HasMaxLength(100);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}