// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CreditCardSystem.Models
{
    public partial class CreditCard
    {
        public Guid CreditCardId { get; set; }
        public string CardNumber { get; set; }
        public DateTime CardExpiry { get; set; }
        public string CardCvv { get; set; }
        public Guid CardTypeId { get; set; }

        public virtual CardType CardType { get; set; }
    }
}