// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CreditCardSystem.Models
{
    public partial class CreditCardSystemContext : DbContext
    {
        public CreditCardSystemContext()
        {
        }

        public CreditCardSystemContext(DbContextOptions<CreditCardSystemContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CardType> CardType { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CardType>(entity =>
            {
                entity.Property(e => e.CardTypeId).ValueGeneratedNever();

                entity.Property(e => e.CardTypeName)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}