// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CreditCardSystem.Models
{
    public partial class ValidationRegex
    {
        public ValidationRegex()
        {
            CardType = new HashSet<CardType>();
        }

        public Guid ValidationRegexId { get; set; }
        public string ValidationRegexString { get; set; }
        public string ValidationRegexName { get; set; }

        public virtual ICollection<CardType> CardType { get; set; }
    }
}